<p>
[ <a href="index.php?table=albums&subtable=tracks">albums</a> ] 
[ <a href="index.php?table=artists">artists</a> ] 
[ <a href="index.php?table=labels">labels</a> ] 
[ <a href="index.php?table=pages">pages</a> ] 
[ <a href="index.php?table=tags">tags</a> ] 
[ <a href="index.php?table=tracks">tracks</a> ] 
[ <a href="index.php?table=types">types</a> ] 
[ <a href="index.php?table=products">products</a> ] 
[ <a href="Reports">Reports</a> ] 
</p>
